File formats reference
----------------------

This section documents the various file formats used/generated by enstaller,
such as our custom egg format.

.. toctree::
   :maxdepth: 1

   egg_format
